// data.js - Dane pomocnicze

// ===== VODKAS =====
export const vodkas = [
    { name: "Belvedere", price: "28,00", country: "Polska", ingredient: "Żyto" },
    { name: "Belvedere Lake Bartężek", price: "39,00", country: "Polska", ingredient: "Żyto" },
    { name: "Chopin Potato", price: "35,00", country: "Polska", ingredient: "Ziemniaki" },
    { name: "Grey Goose", price: "28,00", country: "Francja", ingredient: "Pszenica (ozima)" },
    { name: "Ostoya Vodka", price: "19,00", country: "Polska", ingredient: "Pszenica" },
    { name: "Ostoya Black", price: "21,00", country: "Polska", ingredient: "Pszenica" }
];

// ===== GLASSES =====
export const glassOptions = [
    "Collins",
    "Nick & Nora", 
    "Double Old Fashioned Glass",
    "Coupe + kieliszek do wódki",
    "Old Fashioned",
    "Coupe",
    "Champagne Flute",
    "Irish Coffee Cup",
    "Whisky Glass",
    "Copa Bombay",
    "Copa Martini",
    "Mini Coupette",
    "Swizzle Glass",
    "Hot Toddy Cup",
    "Szkło do koniaku - snifter"
];

// Funkcje pomocnicze dla szklanek
export function getGlassById(glassName) {
    return glassOptions.find(glass => glass === glassName);
}

export function getAllGlasses() {
    return [...glassOptions];
}

export function searchGlasses(searchTerm) {
    return glassOptions.filter(glass =>
        glass.toLowerCase().includes(searchTerm.toLowerCase())
    );
}

// Mapowanie szklanek na kategorie
export const glassCategories = {
    "Koktajlowe": ["Nick & Nora", "Coupe", "Mini Coupette"],
    "Wysokie": ["Collins", "Champagne Flute", "Swizzle Glass"],
    "Niskie": ["Old Fashioned", "Double Old Fashioned Glass", "Whisky Glass"],
    "Specjalne": ["Irish Coffee Cup", "Hot Toddy Cup", "Szkło do koniaku - snifter"],
    "Copa": ["Copa Bombay", "Copa Martini"],
    "Kombinowane": ["Coupe + kieliszek do wódki"]
};

// Szkła dla poszczególnych drinków
export const drinkGlasses = {
    "Bloody Mary": "Collins",
    "Cosmopolitan": "Nick & Nora",
    "Espresso Martini": "Nick & Nora",
    "Golden Cadillac": "Nick & Nora",
    "Grasshooper": "Nick & Nora",
    "Long Island Iced Tea": "Swizzle Glass",
    "Pornstar Martini": "Coupe + kieliszek do wódki",
    "Vodka Sour": "Double Old Fashioned Glass",
    "Kyiv Mule": "Collins",
    "ARM & NAVY": "Nick & Nora",
    "AVIATION": "Nick & Nora",
    "BEE’S KNEES": "Nick & Nora",
    "BIJOU": "Nick & Nora",
    "Bombay & Tonic": "Copa Bombay",
    "BRAMBLE": "Collins",
    "BREAKFAST MARTINI": "Nick & Nora",
    "CHARLIE CHAPLIN": "Nick & Nora",
    "CHRYSANTHEMUM": "Nick & Nora",
    "CLOVER CLUB": "Nick & Nora",
    "Corpse": "Nick & Nora",
    "DRY MARTINI": "Nick & Nora",
    "gimlet": "Nick & Nora",
    "GIN BASIL SMASH": "Old Fashioned",
    "GIN GIN MULE": "Collins",
    "HANKY PANKY": "Nick & Nora",
    "LAST WORD": "Nick & Nora",
    "Martinez": "Nick & Nora",
    "NEGRONI": "Whisky Glass",
    "RAMOS GIN FIZZ": "Collins",
    "SINGAPORE SLING": "Collins",
    "Southside": "Nick & Nora",
    "TUXEDO COCKTAIL": "Nick & Nora",
    "vesper MARTINI": "Mini Coupette",
    "WHITE LADY": "Nick & Nora",
    "white NEGRONI": "Whisky Glass",
    "XX CENTURY COCKTAIL": "Nick & Nora",
    "AIR MAIL": "Champagne Flute",
    "Caipirinha": "Double Old Fashioned Glass",
    "Classic Rum Swizzle": "Collins",
    "Corn 'n' Oil": "Double Old Fashioned Glass",
    "Cuba Libre": "Collins",
    "Daiquiri": "Nick & Nora",
    "Dark 'n' Stormy": "Collins",
    "El Presidente": "Nick & Nora",
    "Fish House Punch": "Collins",
    "Fog Cutter": "Collins",
    "Hemingway Daiquiri": "Nick & Nora",
    "Hot Rum Grog": "Irish Coffee Cup",
    "Mai Tai": "Double Old Fashioned Glass",
    "Mojito": "Collins",
    "Mojito Norblito": "Collins",
    "Nuclear Daiquiri": "Nick & Nora",
    "Old Cuban": "Collins",
    "Queen's Park Swizzle": "Collins",
    "Pisco Sour": "Nick & Nora",
    "Right Hand Cocktail": "Old Fashioned",
    "Zombie": "Collins",
    "PINK CHIHUAHUA": "Nick & Nora",
    "margarita": "Nick & Nora",
    "TOMMY’S MARGARITA": "Old Fashioned",
    "LA PALOMA": "Collins",
    "NEGRONI 0%": "Whisky Glass",
    "Martini Fiero spritz": "Copa Martini",
    "Martini Fiero & Tonik": "Copa Martini",
    "Vibrante/Floreale Tonik": "Copa Martini",
    "Martini vibrante/floreale spritz": "Copa Martini",
    "Amaretto Sour": "Nick & Nora",
    "Blood & Sand": "Nick & Nora",
    "Boulevardier": "Old Fashioned",
    "Manhattan": "Nick & Nora",
    "Whisky Sour": "Double Old Fashioned Glass",
    "Irish Coffee": "Irish Coffee Cup",
    "BRANDY CRUSTA": "Champagne Flute",
    "CAMERON'S KICK": "Old Fashioned",
    "Corpse Reviver #1": "Nick & Nora",
    "Derby": "Nick & Nora",
    "HOT TODDY": "Hot Toddy Cup",
    "JAPANESE COCKTAIL": "Old Fashioned",
    "NEW YORK SOUR": "Double Old Fashioned Glass",
    "Loretto old fashioned": "Old Fashioned",
    "PAPER PLANE": "Nick & Nora",
    "PENICILLIN": "Old Fashioned",
    "Sazerac": "Szkło do koniaku - snifter",
    "TRYNIDAD SOUR": "Nick & Nora",
    "WHISKEY SMASH": "Old Fashioned",
    "VIEUX CAREE": "Old Fashioned",
    "Amaretto Sour": "Nick & Nora",
    "Blood & Sand": "Nick & Nora",
    "Boulevardier": "Old Fashioned",
    "Manhattan": "Nick & Nora",
    "Whisky Sour": "Double Old Fashioned Glass",
    "Irish Coffee": "Irish Coffee Cup",
    "BRANDY CRUSTA": "Champagne Flute",
    "CAMERON'S KICK": "Old Fashioned",
    "Corpse Reviver #1": "Nick & Nora",
    "Derby": "Nick & Nora",
    "HOT TODDY": "Hot Toddy Cup",
    "JAPANESE COCKTAIL": "Old Fashioned",
    "NEW YORK SOUR": "Double Old Fashioned Glass",
    "Loretto old fashioned": "Old Fashioned",
    "PAPER PLANE": "Nick & Nora",
    "PENICILLIN": "Old Fashioned",
    "Sazerac": "Szkło do koniaku - snifter",
    "TRYNIDAD SOUR": "Nick & Nora",
    "WHISKEY SMASH": "Old Fashioned",
    "VIEUX CAREE": "Old Fashioned",
};

// Dekoracje dla poszczególnych drinków
export const drinkDecorations = {
    "Bloody Mary": "Oliwka na szpadce - plus wierzch koktajlu skropiony oliwą truflową - picanto mix na szkle, slice ogórka",
    "Cosmopolitan": "suszony, czerwony kwiatostan róży",
    "Espresso Martini": "tarta fasola tonka + bezik",
    "Golden Cadillac": "Bezik plus gorzka tarta czekolada + złoty pył",
    "Grasshooper": "Bezik plus gorzka tarta czekolada",
    "Long Island Iced Tea": "Plasterek cytryny",
    "Pornstar Martini": "posypka z pudru buraczanego + kwiatostan róży",
    "Vodka Sour": "coin z pomarańczy",
    "Kyiv Mule": "2 szczypy mięty + ćwiartka limonki",
    "ARM & NAVY": "olejki z cytryny + coin z cytryny",
    "AVIATION": "Wiśnia Koktajlowa + olejki cytrynowe",
    "BEE’S KNEES": "zest z pomarańczy przypięty do stópki",
    "BIJOU": "Olejki z cytryny i wiśnia",
    "Bombay & Tonic": "1/4 limonki ułożona po środku koktajlu",
    "BRAMBLE": "kwiat gipsówki",
    "BREAKFAST MARTINI": "olejki pomarańczowe i żółta różyczka położona na wierzchu.",
    "CHARLIE CHAPLIN": "suszony kwiatostan róży",
    "CHRYSANTHEMUM": "zest z cytryny wycięty nożyczkami krawieckimi -",
    "CLOVER CLUB": "na środku koktajlu odrobinę maliny iofilizowanej + kwiat",
    "Corpse": "zest z cytryny wycięty nożyczkami krawieckimi -",
    "DRY MARTINI": "oliwka + olejki cytrynowe",
    "gimlet": "olejki ze skórki grejpfrutowej + 3 krople oliwy mandarynkowej",
    "GIN BASIL SMASH": "3 liście bazylii",
    "GIN GIN MULE": "Bukiet mięty + plasterek ogórka",
    "HANKY PANKY": "coin z pomarańczy",
    "LAST WORD": "olejki z limonki + wiśnia koktajlowa",
    "Martinez": "Wiśnia + olejki pomarańczowe",
    "NEGRONI": "olejki pomarańczowe + kółko ,,coin” z pomarańczy.",
    "RAMOS GIN FIZZ": "1 żółta różyczka + olejki z cytryny",
    "SINGAPORE SLING": "suszka z limonki + wiśnia na szpadce",
    "Southside": "mięta w czipsie limonkowym",
    "TUXEDO COCKTAIL": "olejki cytrynowe + wiśnia",
    "vesper MARTINI": "Zest z cytryny włożony do środka",
    "WHITE LADY": "2 żółte różyczki + olejki cytrynowe",
    "white NEGRONI": "olejki grejpfrutowe + zest z grejpfruta wycięty nożyczkami",
    "XX CENTURY COCKTAIL": "zest z cytryny, przypięty do rantu szkła",
    "AIR MAIL": "3 kosteczki imbiru na szpadce",
    "Caipirinha": "1/4 limonki ułożona po środku koktajlu",
    "Classic Rum Swizzle": "Bukiet mięty + czips z limonki",
    "Corn 'n' Oil": "1/2 limonki",
    "Cuba Libre": "1/4 limonki ułożona po środku koktajlu",
    "Daiquiri": "Zest z limonki",
    "Dark 'n' Stormy": "2 szczypy mięty",
    "El Presidente": "Wiśnia + olejki pomarańczowe",
    "Fish House Punch": "Bukiet mięty (3 szczypy) + ćwiartka cytryny",
    "Fog Cutter": "Bukiet mięty + czips z ananasa - całość oprószona pudrem pomarańczowym",
    "Hemingway Daiquiri": "Olejki grejpfrutowe + wiśnia koktajlowa",
    "Hot Rum Grog": "Laska cynamonu + pół plasterka pomarańczy + kandyzowany imbir",
    "Mai Tai": "Czips z ananasa + bukiet mięty oprószony pudrem",
    "Mojito": "Bukiet mięty oprószony cukrem klasycznym lub cytrusowym",
    "Mojito Norblito": "Bukiet mięty oprószony pudrem klasycznym bądź cytrusowym",
    "Nuclear Daiquiri": "Mięta w czipsie limonkowym",
    "Old Cuban": "Mięta posypana pudrem",
    "Queen's Park Swizzle": "Bukiet mięty + czips z ananasa - całość oprószona pudrem",
    "Pisco Sour": "3 krople Angostura Bitters na wierzchu koktajlu -",
    "Right Hand Cocktail": "Coin z pomarańczy przypięte na spinaczu do rantu szkła",
    "Zombie": "Bukiet mięty + tarta fasola tonka + imbir kandyzowany na szpadce",
    "PINK CHIHUAHUA": "kwiat Gomfreny + pył czerwony",
    "margarita": "Wysokiej jakości sól na rancie (crusta tylko na połowie",
    "TOMMY’S MARGARITA": "czips z ananas",
    "LA PALOMA": "mała ćwiartka grejpfruta + miks przypraw na rancie.",
    "NEGRONI 0%": "olejki pomarańczowe + kółko ,,coin” z pomarańczy.",
    "Martini Fiero spritz": "2 półplastry pomarańczy",
    "Martini Fiero & Tonik": "2 półplastry pomarańczy",
    "Vibrante/Floreale Tonik": "2 półplastry pomarańczy",
    "Martini vibrante/floreale spritz": "2 półplastry pomarańczy",
    "Amaretto Sour": "wierzch koktajlu posypany pudrem buraczanym oraz suszony kwiatostan róży",
    "Blood & Sand": "wiśnia na szpadce + olejki pomarańczowe",
    "Boulevardier": "olejki pomarańczowe + coin z pomarańczy przypięte na spinaczu do rantu szkła",
    "Manhattan": "Wiśnia Koktajlowa + spray z olejków pomarańczowych",
    "Whisky Sour": "coin z pomarańczy",
    "Irish Coffee": "tarta fasola tonka na wierzch + gwiazdka anyżu",
    "BRANDY CRUSTA": "cukier pomarańczowy plus duży zest z pomarańczy",
    "CAMERON'S KICK": "coin z pomarańczy",
    "Corpse Reviver #1": "Olejki cytrynowe (serwujemy bez garnishu)",
    "Derby": "zest z grejpfruta wycięty nożyczkami karbowanymi przypięty do rantu szkła",
    "HOT TODDY": "laska cynamonu + plaster cytryny",
    "JAPANESE COCKTAIL": "Olejki ze skórki cytrynowej + wiśnia koktajlowa",
    "NEW YORK SOUR": "coin z pomarańczy",
    "Loretto old fashioned": "Kółko - coin z pomarańczy położony na bryłce + wiśnia",
    "PAPER PLANE": "Zest z pomarańczy => przypięty do stópki.",
    "PENICILLIN": "kandyzowany imbir na wykałaczce koktajlowej",
    "Sazerac": "olejki ze skórki cytrynowej",
    "TRYNIDAD SOUR": "tarta gorzka czekolada + gwiazdka anyżu",
    "WHISKEY SMASH": "Bukiet mięty opruszony pudrem pomarańczowym",
    "VIEUX CAREE": "coin z cytryny",
    "Amaretto Sour": "wierzch koktajlu posypany pudrem buraczanym oraz suszony kwiatostan róży",
    "Blood & Sand": "wiśnia na szpadce + olejki pomarańczowe",
    "Boulevardier": "olejki pomarańczowe + coin z pomarańczy przypięte na spinaczu do rantu szkła",
    "Manhattan": "Wiśnia Koktajlowa + spray z olejków pomarańczowych",
    "Whisky Sour": "coin z pomarańczy",
    "Irish Coffee": "tarta fasola tonka na wierzch + gwiazdka anyżu",
    "BRANDY CRUSTA": "cukier pomarańczowy plus duży zest z pomarańczy",
    "CAMERON'S KICK": "coin z pomarańczy",
    "Corpse Reviver #1": "Olejki cytrynowe (serwujemy bez garnishu)",
    "Derby": "zest z grejpfruta wycięty nożyczkami karbowanymi przypięty do rantu szkła",
    "HOT TODDY": "laska cynamonu + plaster cytryny",
    "JAPANESE COCKTAIL": "Olejki ze skórki cytrynowej + wiśnia koktajlowa",
    "NEW YORK SOUR": "coin z pomarańczy",
    "Loretto old fashioned": "Kółko - coin z pomarańczy położony na bryłce + wiśnia",
    "PAPER PLANE": "Zest z pomarańczy => przypięty do stópki.",
    "PENICILLIN": "kandyzowany imbir na wykałaczce koktajlowej",
    "Sazerac": "olejki ze skórki cytrynowej",
    "TRYNIDAD SOUR": "tarta gorzka czekolada + gwiazdka anyżu",
    "WHISKEY SMASH": "Bukiet mięty opruszony pudrem pomarańczowym",
    "VIEUX CAREE": "coin z cytryny",
};

export const drinkCategories = {
    "Wódka": [
        "Bloody Mary",
        "Cosmopolitan",
        "Espresso Martini",
        "Golden Cadillac",
        "Grasshooper",
        "Long Island Iced Tea",
        "Pornstar Martini",
        "Vodka Sour",
        "Kyiv Mule",
    ],
    "Gin": [
        "ARM & NAVY",
        "AVIATION",
        "BEE’S KNEES",
        "BIJOU",
        "Bombay & Tonic",
        "BRAMBLE",
        "BREAKFAST MARTINI",
        "CHARLIE CHAPLIN",
        "CHRYSANTHEMUM",
        "CLOVER CLUB",
        "Corpse",
        "DRY MARTINI",
        "gimlet",
        "GIN BASIL SMASH",
        "GIN GIN MULE",
        "HANKY PANKY",
        "LAST WORD",
        "Martinez",
        "NEGRONI",
        "RAMOS GIN FIZZ",
        "SINGAPORE SLING",
        "Southside",
        "TUXEDO COCKTAIL",
        "vesper MARTINI",
        "WHITE LADY",
        "white NEGRONI",
        "XX CENTURY COCKTAIL",
    ],
    "Rum": [
        "AIR MAIL",
        "Caipirinha",
        "Classic Rum Swizzle",
        "Corn \'n\' Oil",
        "Cuba Libre",
        "Daiquiri",
        "Dark \'n\' Stormy",
        "El Presidente",
        "Fish House Punch",
        "Fog Cutter",
        "Hemingway Daiquiri",
        "Hot Rum Grog",
        "Mai Tai",
        "Mojito",
        "Mojito Norblito",
        "Nuclear Daiquiri",
        "Old Cuban",
        "Queen\s Park Swizzle",
        "Pisco Sour",
        "Right Hand Cocktail",
        "Zombie",
    ],
    "Tequila": [
        "PINK CHIHUAHUA",
        "margarita",
        "TOMMY’S MARGARITA",
        "LA PALOMA",
    ],
    "Bezalkoholowe": [
        "NEGRONI 0%",
        "Martini Fiero spritz",
        "Martini Fiero & Tonik",
        "Vibrante/Floreale Tonik",
        "Martini vibrante/floreale spritz",
    ],
    "Whiskey": [
        "Amaretto Sour",
        "Blood & Sand",
        "Boulevardier",
        "Manhattan",
        "Whisky Sour",
        "Irish Coffee",
        "BRANDY CRUSTA",
        "CAMERON\S KICK",
        "Corpse Reviver #1",
        "Derby",
        "HOT TODDY",
        "JAPANESE COCKTAIL",
        "NEW YORK SOUR",
        "Loretto old fashioned",
        "PAPER PLANE",
        "PENICILLIN",
        "Sazerac",
        "TRYNIDAD SOUR",
        "WHISKEY SMASH",
        "VIEUX CAREE",
    ],
};

// Funkcje pomocnicze
export function findDrinkCategory(drinkName) {
    for (const [category, drinks] of Object.entries(drinkCategories)) {
        if (drinks.includes(drinkName)) {
            return category;
        }
    }
    return null;
}

export function getDrinksByCategories(selectedCategories) {
    const drinks = [];
    for (const [category, categoryDrinks] of Object.entries(drinkCategories)) {
        if (selectedCategories.includes(category)) {
            drinks.push(...categoryDrinks);
        }
    }
    return drinks;
}

// Kompatybilność z poprzednią wersją
export const drinkLibrary = drinkCategories;
