// data.js - Dane pomocnicze

// ===== VODKAS =====
export const vodkas = [
    { name: "Belvedere", price: "28,00", country: "Polska", ingredient: "Żyto" },
    { name: "Belvedere Lake Bartężek", price: "39,00", country: "Polska", ingredient: "Żyto" },
    { name: "Chopin Potato", price: "35,00", country: "Polska", ingredient: "Ziemniaki" },
    { name: "Grey Goose", price: "28,00", country: "Francja", ingredient: "Pszenica (ozima)" },
    { name: "Ostoya Vodka", price: "19,00", country: "Polska", ingredient: "Pszenica" },
    { name: "Ostoya Black", price: "21,00", country: "Polska", ingredient: "Pszenica" }
];

// ===== GLASSES =====
export const glassOptions = [
    "Collins",
    "Nick & Nora", 
    "Short",
    "Coupe + kieliszek do wódki",
    "Coupe",
    "Champagne Flute",
    "Irish Coffee Cup",
    "Copa Bombay",
    "Copa Martini",
    "Mini Coupette",
    "Swizzle Glass",
    "Hot Toddy Cup",
    "Szkło do koniaku - snifter"
];

// Funkcje pomocnicze dla szklanek
export function getGlassById(glassName) {
    return glassOptions.find(glass => glass === glassName);
}

export function getAllGlasses() {
    return [...glassOptions];
}

export function searchGlasses(searchTerm) {
    return glassOptions.filter(glass =>
        glass.toLowerCase().includes(searchTerm.toLowerCase())
    );
}

// Mapowanie szklanek na kategorie
export const glassCategories = {
    "Koktajlowe": ["Nick & Nora", "Coupe", "Mini Coupette"],
    "Wysokie": ["Collins", "Champagne Flute", "Swizzle Glass"],
    "Niskie": ["Short"],
    "Specjalne": ["Irish Coffee Cup", "Hot Toddy Cup", "Szkło do koniaku - snifter"],
    "Copa": ["Copa Bombay", "Copa Martini"],
    "Kombinowane": ["Coupe + kieliszek do wódki"]
};

// Szkła dla poszczególnych drinków
export const drinkGlasses = {
    "Bloody Mary": "Collins",
    "Cosmopolitan": "Nick & Nora",
    "Espresso Martini": "Nick & Nora",
    "Golden Cadillac": "Nick & Nora",
    "Grasshooper": "Nick & Nora",
    "Long Island Iced Tea": "Swizzle Glass",
    "Pornstar Martini": "Coupe + kieliszek do wódki",
    "Vodka Sour": "Short",
    "Kyiv Mule": "Collins",
    "ARM & NAVY": "Nick & Nora",
    "AVIATION": "Nick & Nora",
    "BEE'S KNEES": "Nick & Nora",
    "BIJOU": "Nick & Nora",
    "Bombay & Tonic": "Copa Bombay",
    "BRAMBLE": "Collins",
    //"BREAKFAST MARTINI": "Nick & Nora",
    "CHARLIE CHAPLIN": "Nick & Nora",
    "CHRYSANTHEMUM": "Nick & Nora",
    "CLOVER CLUB": "Nick & Nora",
    "Corpse Reviver #2": "Nick & Nora",
    "DRY MARTINI": "Nick & Nora",
    "gimlet": "Nick & Nora",
    "GIN BASIL SMASH": "Short",
    "GIN GIN MULE": "Collins",
    "HANKY PANKY": "Nick & Nora",
    "LAST WORD": "Nick & Nora",
    "Martinez": "Nick & Nora",
    "NEGRONI": "Short",
    "RAMOS GIN FIZZ": "Collins",
    "SINGAPORE SLING": "Collins",
    "Southside": "Nick & Nora",
    "TUXEDO COCKTAIL": "Nick & Nora",
    "vesper MARTINI": "Mini Coupette",
    "WHITE LADY": "Nick & Nora",
    "white NEGRONI": "Short",
    "XX CENTURY COCKTAIL": "Nick & Nora",
    "AIR MAIL": "Champagne Flute",
    "Caipirinha": "Short",
    "Classic Rum Swizzle": "Swizzle Glass",
    "Corn 'n' Oil": "Short",
    "Cuba Libre": "Collins",
    "Daiquiri": "Nick & Nora",
    "Dark 'n' Stormy": "Collins",
    "El Presidente": "Nick & Nora",
    "Fish House Punch": "Collins",
    "Fog Cutter": "Collins",
    "Hemingway Daiquiri": "Nick & Nora",
    "Hot Rum Grog": "Irish Coffee Cup",
    "Mai Tai": "Short",
    "Mojito": "Swizzle Glass",
    "Mojito Norblito": "Collins",
    "Nuclear Daiquiri": "Nick & Nora",
    "Old Cuban": "Collins",
    "Queen's Park Swizzle": "Swizzle Glass",
    "Pisco Sour": "Nick & Nora",
    "Right Hand Cocktail": "Short",
    "Zombie": "Collins",
    "PINK CHIHUAHUA": "Nick & Nora",
    "margarita": "Nick & Nora",
    "TOMMY'S MARGARITA": "Short",
    "LA PALOMA": "Collins",
    "NEGRONI 0%": "Short",
    //"Martini Fiero spritz": "Copa Martini",
    //"Martini Fiero & Tonik": "Copa Martini",
    //"Vibrante/Floreale Tonik": "Copa Martini",
    //"Martini vibrante/floreale spritz": "Copa Martini",
    "Amaretto Sour": "Nick & Nora",
    "Blood & Sand": "Nick & Nora",
    "Boulevardier": "Short",
    "Manhattan": "Nick & Nora",
    "Whisky Sour": "Short",
    "Irish Coffee": "Irish Coffee Cup",
    "BRANDY CRUSTA": "Champagne Flute",
    "CAMERON'S KICK": "Short",
    "Corpse Reviver #1": "Nick & Nora",
    "Derby": "Nick & Nora",
    "HOT TODDY": "Hot Toddy Cup",
    "JAPANESE COCKTAIL": "Short",
    "NEW YORK SOUR": "Short",
    "Loretto old fashioned": "Short",
    "Old fashioned": "Short",
    "PAPER PLANE": "Nick & Nora",
    "PENICILLIN": "Short",
    "Sazerac": "Szkło do koniaku - snifter",
    "TRYNIDAD SOUR": "Nick & Nora",
    "WHISKEY SMASH": "Short",
    "VIEUX CAREE": "Short",
};

// Dekoracje dla poszczególnych drinków
export const drinkDecorations = {
"Vodka Sour": "coin z pomarańczy",
"HANKY PANKY": "coin z pomarańczy",
"Whisky Sour": "coin z pomarańczy",
"NEW YORK SOUR": "coin z pomarańczy",
"CAMERON'S KICK": "coin z pomarańczy",
"VIEUX CAREE": "coin z cytryny",
"ARM & NAVY": "olejki cytrynowe + coin z cytryny",
"NEGRONI": "olejki pomarańczowe + coin z pomarańczy",
"NEGRONI 0%": "olejki pomarańczowe + coin z pomarańczy",
"Loretto old fashioned": "Coin z pomarańczy położony na bryłce + wiśnia",
"Old fashioned": "Coin z pomarańczy położony na bryłce + wiśnia",
"vesper MARTINI": "Zest z cytryny włożony do środka",
"Daiquiri": "Zest z limonki",
"Derby": "zest z grejpfruta wycięty nożyczkami karbowanymi przypięty do rantu szkła",
"Boulevardier": "olejki pomarańczowe + coin z pomarańczy przypięte na spinaczu do rantu szkła",
"Right Hand Cocktail": "Coin z pomarańczy przypięte na spinaczu do rantu szkła",
"XX CENTURY COCKTAIL": "zest z cytryny, przypięty do rantu szkła",
"BEE'S KNEES": "zest z pomarańczy przypięty do stópki",
"PAPER PLANE": "zest z pomarańczy przypięty do stópki",
"CHRYSANTHEMUM": "zest z cytryny wycięty nożyczkami krawieckimi - karbowanymi",
"Corpse Reviver #2": "zest z cytryny wycięty nożyczkami krawieckimi - karbowanymi",
"white NEGRONI": "olejki grejpfrutowe + zest z grejpfruta wycięty nożyczkami karbowanymi / krawieckimi",
"AVIATION": "Wiśnia Koktajlowa + olejki cytrynowe",
"JAPANESE COCKTAIL": "Wiśnia Koktajlowa + olejki cytrynowe",
"BIJOU": "Wiśnia Koktajlowa + olejki cytrynowe",
"TUXEDO COCKTAIL": "Wiśnia Koktajlowa + olejki cytrynowe",
"LAST WORD": "Wiśnia Koktajlowa + olejki z limonki",
"Martinez": "Wiśnia Koktajlowa + olejki pomarańczowe",
"El Presidente": "Wiśnia Koktajlowa + olejki pomarańczowe",
"Manhattan": "Wiśnia Koktajlowa + olejki pomarańczowe",
"Hemingway Daiquiri": "Wiśnia Koktajlowa + olejki grejpfrutowe",
"SINGAPORE SLING": "wiśnia na szpadce + suszka z limonki",
"Blood & Sand": "wiśnia na szpadce + olejki pomarańczowe",
"gimlet": "olejki grejpfrutowe + 3 krople oliwy mandarynkowej",
"Corpse Reviver #1": "Olejki cytrynowe",
"Sazerac": "Olejki cytrynowe",
"Long Island Iced Tea": "Plasterek cytryny",
"Bombay & Tonic": "1/4 limonki ułożona po środku koktajlu",
"Caipirinha": "1/4 limonki ułożona po środku koktajlu",
"Cuba Libre": "1/4 limonki ułożona po środku koktajlu",
"Corn 'n' Oil": "1/2 limonki",
"Martini Fiero spritz": "2 półplastry pomarańczy",
"Martini Fiero & Tonik": "2 półplastry pomarańczy",
"Vibrante/Floreale Tonik": "2 półplastry pomarańczy",
"Martini vibrante/floreale spritz": "2 półplastry pomarańczy",
"Southside": "Mięta w czipsie limonkowym",
"Nuclear Daiquiri": "Mięta w czipsie limonkowym",
"Classic Rum Swizzle": "Bukiet mięty + czips z limonki",
"TOMMY'S MARGARITA": "czips z ananas",
"Kyiv Mule": "2 szczypy mięty + ćwiartka limonki",
"Dark 'n' Stormy": "2 szczypy mięty",
"Fish House Punch": "3 szczypy mięty + ćwiartka cytryny",
"Fog Cutter": "Bukiet mięty + czips z ananasa - całość oprószona pudrem pomarańczowym",
"Queen's Park Swizzle": "Bukiet mięty + czips z ananasa - całość oprószona pudrem",
"Mai Tai": "Czips z ananasa + bukiet mięty oprószony pudrem",
"Mojito": "Bukiet mięty oprószony cukrem klasycznym lub cytrusowym",
"Mojito Norblito": "Bukiet mięty oprószony pudrem klasycznym lub cytrusowym",
"WHISKEY SMASH": "Bukiet mięty oprószony pudrem pomarańczowym",
"Old Cuban": "Mięta posypana pudrem",
"Zombie": "Bukiet mięty + tarta fasola tonka + imbir kandyzowany na szpadce",
"GIN GIN MULE": "Bukiet mięty + plasterek ogórka",
"GIN BASIL SMASH": "3 liście bazylii",
"Cosmopolitan": "suszony, czerwony kwiatostan róży",
"CHARLIE CHAPLIN": "suszony, czerwony kwiatostan róży",
"BRAMBLE": "kwiat gipsówki",
"BREAKFAST MARTINI": "żółta różyczka + olejki pomarańczowe",
"RAMOS GIN FIZZ": "żółta różyczka + olejki cytrynowe",
"WHITE LADY": "2 żółte różyczki + olejki cytrynowe",
"CLOVER CLUB": "na środku koktajlu odrobinę maliny liofilizowanej + kwiat gomfreny",
"PINK CHIHUAHUA": "kwiat Gomfreny + pył czerwony",
"DRY MARTINI": "oliwka + olejki cytrynowe",
"AIR MAIL": "3 kosteczki imbiru na szpadce",
"PENICILLIN": "kandyzowany imbir na szpadce",
"Hot Rum Grog": "Laska cynamonu + pół plasterka pomarańczy + kandyzowany imbir",
"HOT TODDY": "laska cynamonu + plaster cytryny",
"Irish Coffee": "tarta fasola tonka na wierzch + gwiazdka anyżu",
"TRYNIDAD SOUR": "tarta gorzka czekolada + gwiazdka anyżu",
"Espresso Martini": "Bezik + tarta fasola tonka",
"Golden Cadillac": "Bezik plus gorzka tarta czekolada + złoty pył",
"Grasshooper": "Bezik plus gorzka tarta czekolada",
"Amaretto Sour": "posypka z pudru buraczanego + kwiatostan róży",
"Pornstar Martini": "posypka z pudru buraczanego + kwiatostan róży",
"BRANDY CRUSTA": "cukier pomarańczowy plus duży zest z pomarańczy",
"LA PALOMA": "mała ćwiartka grejpfruta + miks przypraw na rancie.",
"margarita": "Wysokiej jakości sól na rancie (crusta tylko na połowie szkła) i czips z limonki.",
"Pisco Sour": "3 krople Angostura Bitters na wierzchu koktajlu - przecinamy je szpadką koktajlową w celu stworzenia serduszek.",
"Bloody Mary": "Oliwka na szpadce - plus wierzch koktajlu skropiony oliwą truflową - picanto mix na szkle, slice ogórka",
};

export const drinkCategories = {
    "Wódka": [
        "Bloody Mary",
        "Cosmopolitan",
        "Espresso Martini",
        "Golden Cadillac",
        "Grasshooper",
        "Long Island Iced Tea",
        "Pornstar Martini",
        "Vodka Sour",
        "Kyiv Mule",
    ],
    "Gin": [
        "ARM & NAVY",
        "AVIATION",
        "BEE'S KNEES",
        "BIJOU",
        "Bombay & Tonic",
        "BRAMBLE",
        "BREAKFAST MARTINI",
        "CHARLIE CHAPLIN",
        "CHRYSANTHEMUM",
        "CLOVER CLUB",
        "Corpse Reviver #2",
        "DRY MARTINI",
        "gimlet",
        "GIN BASIL SMASH",
        "GIN GIN MULE",
        "HANKY PANKY",
        "LAST WORD",
        "Martinez",
        "NEGRONI",
        "RAMOS GIN FIZZ",
        "SINGAPORE SLING",
        "Southside",
        "TUXEDO COCKTAIL",
        "vesper MARTINI",
        "WHITE LADY",
        "white NEGRONI",
        "XX CENTURY COCKTAIL",
    ],
    "Rum": [
        "AIR MAIL",
        "Caipirinha",
        "Classic Rum Swizzle",
        "Corn 'n' Oil",
        "Cuba Libre",
        "Daiquiri",
        "Dark 'n' Stormy",
        "El Presidente",
        "Fish House Punch",
        "Fog Cutter",
        "Hemingway Daiquiri",
        "Hot Rum Grog",
        "Mai Tai",
        "Mojito",
        "Mojito Norblito",
        "Nuclear Daiquiri",
        "Old Cuban",
        "Queen's Park Swizzle",
        "Pisco Sour",
        "Right Hand Cocktail",
        "Zombie",
    ],
    "Tequila": [
        "PINK CHIHUAHUA",
        "margarita",
        "TOMMY'S MARGARITA",
        "LA PALOMA",
    ],
    "Bezalkoholowe": [
        "NEGRONI 0%",
        "Martini Fiero spritz",
        "Martini Fiero & Tonik",
        "Vibrante/Floreale Tonik",
        "Martini vibrante/floreale spritz",
    ],
    "Whiskey": [
        "Amaretto Sour",
        "Blood & Sand",
        "Boulevardier",
        "Manhattan",
        "Whisky Sour",
        "Irish Coffee",
        "BRANDY CRUSTA",
        "CAMERON'S KICK",
        "Corpse Reviver #1",
        "Derby",
        "HOT TODDY",
        "JAPANESE COCKTAIL",
        "NEW YORK SOUR",
        "Loretto old fashioned",
        "Old fashioned",
        "PAPER PLANE",
        "PENICILLIN",
        "Sazerac",
        "TRYNIDAD SOUR",
        "WHISKEY SMASH",
        "VIEUX CAREE",
    ],
};

// Funkcje pomocnicze
export function findDrinkCategory(drinkName) {
    for (const [category, drinks] of Object.entries(drinkCategories)) {
        if (drinks.includes(drinkName)) {
            return category;
        }
    }
    return null;
}

export function getDrinksByCategories(selectedCategories) {
    const drinks = [];
    for (const [category, categoryDrinks] of Object.entries(drinkCategories)) {
        if (selectedCategories.includes(category)) {
            drinks.push(...categoryDrinks);
        }
    }
    return drinks;
}

// Kompatybilność z poprzednią wersją
export const drinkLibrary = drinkCategories;
